### ISSUE TITLE
callback not always listening

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#10]
Hello,

pour apprendre le code de mes télécomandes physiques pour les spécifier dans la partie mapping et setting, j'ai du redémarrer le plugin après chaque écoute car les trames suivantes n'étaient plus captées.

D'autre part, mon Host démarre tous les matins 06h00. le plugin a capté une 10aine trames jusqu'à 07h15. Celles-ci ne sont pas ce que j'ai spécifié dans les paramètres du plugin.
Quand je me suis levé pour ouvrir les volets, rien n'a été capté ...

Après re démarrage du plugin, les trames de mes VR sont captées de nouveau

**Comment by FlyingDomotic** [comment]
J'aurais besoin du fichier domoticz.log (à minima toutes les lignes du plug-in) et du fichier AirSendWebService.log pour voir ce qui passe et ce qui bloque.

**Comment by rezzalex** [comment]
Voici les Logs Arisend.
[AirSendWebService.log](https://github.com/FlyingDomotic/domoticz-airsend-plugin/files/10579236/AirSendWebService.log)


Je viens juste d'activer l'enregistrement des Logs de DZ dans un fichier hors de mon container, je ne peux donc rien fournir pour l'instant mais j'en aurais à l'avenir.

**Comment by rezzalex** [comment]
Logs de DZ, 6 min après redémarage du container, ou l'écoute n'a pas fonctionné...
[domoticz.log](https://github.com/FlyingDomotic/domoticz-airsend-plugin/files/10579438/domoticz.log)

**Comment by FlyingDomotic** [comment]
Concernant le log de Domoticz, les messages indiquent :

> 2023-02-03 14:30:40.071  AirSend: onDeviceModified 001/AirSend - AirSend event data
> 2023-02-03 14:30:40.071  AirSend: Received event {"type":3,"timestamp":"2023-02-03 13:30:39","reliability":7,"channel":{"id":14177,"source":1513505537,"mac":62251},"thingnotes":{"notes":[{"method":1,"type":1,"value":93848611,"value_binsize":32}]},"original_timestamp":1675431039947,"localip":"FE80000000000000DCF6E5FFFE8D2E9A"}
>2023-02-03 14:30:40.072  AirSend: Can't find 14177/1513505537 in YAML configuration file
>2023-02-03 14:30:40.977  AirSend: onDeviceModified 001/AirSend - AirSend event data
>2023-02-03 14:30:40.978  AirSend: Received event {"type":3,"timestamp":"2023-02-03 13:30:40","reliability":7,"channel":{"id":14177,"source":2201174785,"mac":17203},"thingnotes":{"notes":[{"method":1,"type":1,"value":93848618,"value_binsize":32}]},"original_timestamp":1675431040826,"localip":"FE80000000000000DCF6E5FFFE8D2E9A"}
>2023-02-03 14:30:40.978  AirSend: Can't find 14177/2201174785 in YAML configuration file
>2023-02-03 14:30:41.230  AirSend: onDeviceModified 001/AirSend - AirSend event data
>2023-02-03 14:30:41.230  AirSend: Received event {"type":3,"timestamp":"2023-02-03 13:30:41","reliability":7,"channel":{"id":14177,"source":1513505537,"mac":62938},"thingnotes":{"notes":[{"method":1,"type":1,"value":24025759744,"value_binsize":40}]},"original_timestamp":1675431041146,"localip":"FE80000000000000DCF6E5FFFE8D2E9A"}
>2023-02-03 14:30:41.230  AirSend: Can't find 14177/1513505537 in YAML configuration file

Le plug-in reçoit des messages du protocole `14177` depuis le device `1513505537` et `2201174785`, mais ne les trouve pas dans le fichier configuration.yaml. Du coup, ils sont ignorés, ne sachant pas à quoi ça correspond.

Il faudrait vérifier que le fichier configuration.yaml listant l'ensemble des télécommandes AirSend est bien en ligne avec les télécommandes déclarées. Le cas échéant, utiliser l'appli DevMel pour en regénérer un à jour.

Par contre, le fichier AirSendWebService.log s'arrête à 13:11Z alors que le Domoticz indique ces messages à 13:30Z. Ceci dit, le diag du log de Domoticz est clair.

**Comment by FlyingDomotic** [comment]
Est-ce que le problème a été réglé avec les remarques ci-dessus ?

**Comment by rezzalex** [comment]
Bonjour,
Je suis en vacs et essaierai lundi prochain.

Merci en ts cas

Le jeu. 9 févr. 2023, 10:45, Flying Domotic ***@***.***> a
écrit :

**Comment by rezzalex** [comment]
Bonjour, 

les logs de l'airsend webservice sont une heure avant l'heure de DZ et de mon host. J'ai tout essayé pour que ce container (du webservice) soit aligné mais rien n'y fait. Cela n'a pas l'air de gêner quoi que ce soit..

Donc après redémarrage du webservice et du plugin DZ, tout fonctionne, sauf un "UP" d'un VR qui n'est jamais détécté... pb de pile dans la télécommande physique ?

qq minutes après ces tests (vers 16h40), plus rien n'est détecté...

[AirSendWebService.log](https://github.com/FlyingDomotic/domoticz-airsend-plugin/files/10723886/AirSendWebService.log)


[domoticz.log](https://github.com/FlyingDomotic/domoticz-airsend-plugin/files/10723875/domoticz.log)

**Comment by FlyingDomotic** [comment]
Concernant le log AirSend, il semble que l'heure soit en UTC (GMT), ce qui explique la différence d'une heure en hiver.

En lisant le log  Domoticz, il semble qu'il y ait une palanquée de télécommandes non reconnues (63 occurrences en 17h)  :
14177/2201174784
14177/2201174785
14177/1513505536
14177/1536610834
14177/1513505537
1648/59004793670
25457/21905865
25457/23822793
25457/162939337
25457/1458633
25457/15614409
25457/11387337
25457/31228819
25457/5652937
25457/11957961
25457/23896978
25457/23949769
25457/146152685
25457/23869915
25457/23928045
25457/23888786
25457/95448389
25457/23869901
25457/23886241

Concernant l'inactivité, il y a eu 101 messsages reçus entre 16h40 et 16h43, tous traités à l'exception de 2, envoyés depuis des télécommandes non reconnues (25457/23886241 et 14177/2201174785).

Tous les messages étaient sur l'ID 25457, les sources 11928787, 11943087, 11943120, 
11944393, 23886241), tous method 1, type 1, value 2, 4 et 8.

J'ai peut-être raté quelques vérifs, mais  à priori l'ensemble des commandes a bien été passée à Domoticz (value 2 -> nValue to 1, sValue to 0, value 4 -> nValue to 17, sValue to 0, value 8 -> nValue to 0, sValue to 100).

Dans le même temps, le log AirSend indique bien toujours recevoir les commandes bind, ce qui prouve que le plug-in ,n'est pas crashé (on aurait d'ailleurs un/des messages dans le log dans ce cas.

Par contre, ce qui est bizarre, c'est qu'on écoute le protocole 25455, et qu'on reçoit des messages des protocoles 25457 et 14177 ... Une idée ?

**Comment by FlyingDomotic** [comment]
Est-ce que ce problème a été solutionné ?

**Comment by rezzalex** [comment]
Hello.
Pas encore eu le temps de re-regarder, c'est moins critique de mon côté.

**Comment by rezzalex** [comment]
Bonjour, 
j'ai repris le sujet abandonné depuis un certain temps...
J'avais par erreur désactivé mon serveur web PHP sur mon Host ...
Je l'ai remis, je vais continuer d'observer.

**Comment by FlyingDomotic** [comment]
Quoi de neuf, docteur ?

**Comment by rezzalex** [comment]
Ca à l'air tout bon a priori.
Assez difficile à observer dans le temps et dans la constance et rigueur que cela demande.
Si ma confg est bonne, je dois TOUJOURS avoir le bon état sur mes devices Volets DZ.
Je ne sais plus comment j'ai fait, mais j'ai passé mon container AirsedWebService en CET, l'heure "système" de ce container est bonne mais le message capté par Domoticz est tjrs 1 heure avant :  

![image](https://github.com/FlyingDomotic/domoticz-airsend-plugin/assets/35136439/75a9e0aa-3d8d-48b2-b253-0d4a910df2c9)


![image](https://github.com/FlyingDomotic/domoticz-airsend-plugin/assets/35136439/6700a31e-0b04-4429-a992-a91fc7028b58)

**Comment by FlyingDomotic** [comment]
En fait, il y a 2 heures différentes, à 2 endroits différents :

1) dans le message Json envoyé par le plug-in AirSend : c'est visiblement une 
heure GMT. C'est celle entourée dans l'image envoyée. Elle est gérée par AirSend.

2) dans le device "Airsend device data" de Domoticz, la lastSeenDate, qui est 
locale à la machine Domoticz. Elle est exprimée dans l’unité de temps de cette 
machine et est gérée par Domoticz.

Perso, je pense que travailler en heure GMT est une bonne idée, car elle est 
continue, sans doublons ni ambiguïté au passage de l'heure d'hiver. Probablement 
une habitude de pilote ;-)

Pour info, si le calcul de l'heure est bien fait, on devrait avoir + 2h en été, 
et seulement +1h en hiver en France.

Le 05/11/2023 à 11:37, RezzA a écrit :
> Ca à l'air tout bon a priori.
> Assez difficile à observer dans le temps et dans la constance et rigueur que 
> cela demande.
> Si ma confg est bonne, je dois TOUJOURS avoir le bon état sur mes devices 
> Volets DZ.
> Je ne sais plus comment j'ai fait, mais j'ai passé mon container 
> AirsedWebService en CET, l'heure "système" de ce container est bonne mais le 
> message capté par Domoticz est tjrs 1 heure avant :
>
> ![image](https://github.com/FlyingDomotic/domoticz-airsend-plugin/assets/35136439/75a9e0aa-3d8d-48b2-b253-0d4a910df2c9)
>
>
> ![image](https://github.com/FlyingDomotic/domoticz-airsend-plugin/assets/35136439/6700a31e-0b04-4429-a992-a91fc7028b58)
>
>

**Comment by rezzalex** [comment]
Pour le container qui fait tourner mon AirSendWebservice Local, c'est bien une heure CET, voir la capture d'écran du container.

J'ai tjrs des captures de trames qui sont aléatoirement captées ou non par DZ ....

**Comment by FlyingDomotic** [comment]
En fait, tout dépend de ce qu'on demande dans le prog. Même sur des ESP, il est 
possible de récupérer l'heure GMT, l'heure paramétrée sur la machine, et même 
l'heure dans un fuseau horaire dans lequel on n'est pas (par exemple Pacific 
time). Visiblement, AirSend a décidé d'utiliser l'heure GMT dans ses messages, 
ce qui n'est pas idiot. Par contre, l'heure de DZ est la bonne (sous réserve que 
la machine soit correctement paramétrée dans le bon fuseau horaire). Après, sauf 
cas spécifique, on n'analyse pas l'heure du message, donc ce n'est pas très 
grave ...

Ce qui est plus embêtant, ce sont les trames pas captées par DZ. Reste a voir si 
elles sont perdues, ou bien envoyées mais avec un device id incorrect.

Pour avancer, quand il y a un souci de mise à jour, il faut m'envoyer le log du 
Web service AirSend et le log de Domoticz, on verra ce qui se perd ou n'est pas 
compris ...

Le 05/11/2023 à 14:14, RezzA a écrit :
> Pour le container qui fait tourner mon AirSendWebservice Local, c'est bien une heure CET, voir la capture d'écran du container.
>
> J'ai tjrs des captures de trames qui sont aléatoirement captées ou non par DZ ....
>

**Comment by rezzalex** [comment]
19h40; capté 2 fois les commandes montée, arrété , puis pas capté les suivants, jusqu a ce que ca remarche à 19h48

	{"Tous les Volets": {"remoteId": 25457, "remoteSource": 10740368, "deviceId": 25455, "deviceSource": 184423}},

Voit-on un écart entre log AirSendWebService et DZ ?  :  

2023-11-05 19:38:44 	 POST /airsend/bind 90
2023-11-05 19:38:44 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:38:44 	 192.168.1.77 - response 200
2023-11-05 19:39:43 	 POST /airsend/bind 90
2023-11-05 19:39:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:39:43 	 192.168.1.77 - response 200
2023-11-05 19:40:43 	 POST /airsend/bind 90
2023-11-05 19:40:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:40:43 	 192.168.1.77 - response 200
2023-11-05 19:41:43 	 POST /airsend/bind 90
2023-11-05 19:41:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:41:43 	 192.168.1.77 - response 200
2023-11-05 19:42:43 	 POST /airsend/bind 90
2023-11-05 19:42:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:42:43 	 192.168.1.77 - response 200
2023-11-05 19:43:43 	 POST /airsend/bind 90
2023-11-05 19:43:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:43:43 	 192.168.1.77 - response 200
2023-11-05 19:44:43 	 POST /airsend/bind 90
2023-11-05 19:44:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:44:43 	 192.168.1.77 - response 200
2023-11-05 19:45:43 	 POST /airsend/bind 90
2023-11-05 19:45:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:45:43 	 192.168.1.77 - response 200
2023-11-05 19:46:43 	 POST /airsend/bind 90
2023-11-05 19:46:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:46:43 	 192.168.1.77 - response 200
2023-11-05 19:47:43 	 POST /airsend/bind 90
2023-11-05 19:47:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:47:43 	 192.168.1.77 - response 200
2023-11-05 19:48:43 	 POST /airsend/bind 90
2023-11-05 19:48:43 	 192.168.1.77 - POST /airsend/bind 90
2023-11-05 19:48:43 	 192.168.1.77 - response 200



![image](https://github.com/FlyingDomotic/domoticz-airsend-plugin/assets/35136439/d12952ee-e8a7-4e7b-99ce-c84076e6874f)



je suis surpris de constaté qu'il semble y avoir moins de "BIND" coté AirsendWebService que du coté DZ, étrange non ?

**Comment by FlyingDomotic** [comment]
Y'a moyen de récupérer le fichier Domoticz.log (éventuellement expurgé de tout 
ce qui n'est pas AirSend) ?

Le 05/11/2023 à 19:48, RezzA a écrit :
> 19h40; capté 2 fois les commandes montée, arrété , puis pas capté les suivants :
>
> 	{"Tous les Volets": {"remoteId": 25457, "remoteSource": 10740368, "deviceId": 25455, "deviceSource": 184423}},
>
> Voit-on un écart entre log AirSendWebService et DZ ?  :
>
> 2023-11-05 19:33:11 	 POST /airsend/bind 90
> 2023-11-05 19:33:11 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:33:11 	 192.168.1.77 - response 200
> 2023-11-05 19:34:11 	 POST /airsend/bind 90
> 2023-11-05 19:34:11 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:34:11 	 192.168.1.77 - response 200
> 2023-11-05 19:35:11 	 POST /airsend/bind 90
> 2023-11-05 19:35:11 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:35:11 	 192.168.1.77 - response 200
> 2023-11-05 19:36:11 	 POST /airsend/bind 90
> 2023-11-05 19:36:11 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:36:11 	 192.168.1.77 - response 200
> 2023-11-05 19:37:11 	 POST /airsend/bind 90
> 2023-11-05 19:37:11 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:37:11 	 192.168.1.77 - response 200
> 2023-11-05 19:38:11 	 POST /airsend/bind 90
> 2023-11-05 19:38:11 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:38:11 	 192.168.1.77 - response 200
> 2023-11-05 19:38:40 	 GET /airsend/close 0
> 2023-11-05 19:38:40 	 192.168.1.77 - GET /airsend/close 0
> 2023-11-05 19:38:40 	 192.168.1.77 - response 200
> 2023-11-05 19:38:44 	 POST /airsend/bind 90
> 2023-11-05 19:38:44 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:38:44 	 192.168.1.77 - response 200
> 2023-11-05 19:39:43 	 POST /airsend/bind 90
> 2023-11-05 19:39:43 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:39:43 	 192.168.1.77 - response 200
> 2023-11-05 19:40:43 	 POST /airsend/bind 90
> 2023-11-05 19:40:43 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:40:43 	 192.168.1.77 - response 200
> 2023-11-05 19:41:43 	 POST /airsend/bind 90
> 2023-11-05 19:41:43 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:41:43 	 192.168.1.77 - response 200
> 2023-11-05 19:42:43 	 POST /airsend/bind 90
> 2023-11-05 19:42:43 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:42:43 	 192.168.1.77 - response 200
> 2023-11-05 19:43:43 	 POST /airsend/bind 90
> 2023-11-05 19:43:43 	 192.168.1.77 - POST /airsend/bind 90
> 2023-11-05 19:43:43 	 192.168.1.77 - response 200
>
>
> ![image](https://github.com/FlyingDomotic/domoticz-airsend-plugin/assets/35136439/0e121c5d-3efd-472a-8f24-571a58822e1c)
>
>
> je suis surpris de constaté qu'il semble y avoir moins de "BIND" coté AirsendWebService que du coté DZ, étrange non ?
>
>
>   
>

**Comment by FlyingDomotic** [comment]
Des news ?
