### ISSUE TITLE
multiple callback mapping in the same DZ devices

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#11]
Bonjour,

j'ai essayé de mappé ma télécommande physique "centrale" à plusieurs VR, sans succès.

![image](https://user-images.githubusercontent.com/35136439/216287821-55ba43ed-9e4a-4b6c-b777-bf64806548c0.png)

Lors de l'actionnage de cette télécommande centrale, les logs du pmlugin indiquent un mapping seulement sur le dernier spécifié.

**Comment by FlyingDomotic** [comment]
Si je comprends bien, le souci se situe au niveau de la télécommande "Tous les Volets".

Pour le moment, le comportement du plug-in est conforme à celui que j'ai programmé, à savoir associer une (ou plusieurs) télécommande(s) à une autre. Je n'ai pas prévu d'associer une télécommande à plusieurs autres, dans le sens "distribution" (un remote vers plusieurs device) mais bien dans le sens "collecte" (plusieurs remotes vers un seul device, celui enregistré dans configuration.yaml).

Pour régler le cas de "Tous les volets", il faut utiliser Domoticz, et propager le changement d'état à la liste des volets concernés par un petit script (je dois pouvoir aider si besoin). On pourrait même utiliser l'appui sur la télécommande centrale pour déclencher un scénario, et y inclure la liste de volets.

**Comment by rezzalex** [comment]
Merci.
 j'ai fait mes scripts DZVent; ca fonctionne
