### ISSUE TITLE
plus de fonctionnement depuis qq jours

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#13]
Bonjour,
Depuis le 27/10, je recois des erreurs 500 lors de l'appel au local web server :

> 2023-10-30 15:35:33.874 Error: AirSend: Error 500 in POST http://127.0.0.1:33863/airsend/transfer, data {"wait": true, "channel": {"id":"25455","source":"127079"}, "thingnotes":{"notes":[{"method":1,"type":1,"value":8}]}}
> 2023-10-30 15:35:39.115 Error: AirSend: Error 500 in POST http://127.0.0.1:33863/airsend/transfer, data {"wait": true, "channel": {"id":"25455","source":"127079"}, "thingnotes":{"notes":[{"method":1,"type":1,"value":2}]}}
> 2023-10-30 15:35:44.348 Error: AirSend: Error 500 in POST http://127.0.0.1:33863/airsend/transfer, data {"wait": true, "channel": {"id":"25455","source":"127079"}, "thingnotes":{"notes":[{"method":1,"type":1,"value":4}]}}

à ma connaissance; rien n'a changé dans ma configuration.

mon service AirSendWebService tourne, je l'ai même mis à jour.... pas mieux.

Suis-je le seul ?

voici les logs sur AirSendWebServer :  

> 2023-10-30 15:54:54 	 Started as daemon
> 2023-10-30 15:55:15 	 POST /airsend/bind 90
> 2023-10-30 15:55:15 	 handler : size 0 ; new 0x7fc2b0000f20
> 2023-10-30 15:55:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 15:55:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 15:55:15 	 POST /airsend/transfer 117
> 2023-10-30 15:55:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/transfer 117
> 2023-10-30 15:55:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - {"wait":true,"channel":{"id":"25455","source":"241767"},"thingnotes":{"notes":[{"method":1,"type":1,"value":8}]}}
> 2023-10-30 15:55:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - wait 25 - trevents 1
> 2023-10-30 15:55:20 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 500
> 2023-10-30 15:56:15 	 POST /airsend/bind 90
> 2023-10-30 15:56:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 15:56:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 15:57:15 	 POST /airsend/bind 90
> 2023-10-30 15:57:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 15:57:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 15:58:15 	 POST /airsend/bind 90
> 2023-10-30 15:58:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 15:58:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 15:59:15 	 POST /airsend/bind 90
> 2023-10-30 15:59:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 15:59:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:00:15 	 POST /airsend/bind 90
> 2023-10-30 16:00:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:00:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:01:15 	 POST /airsend/bind 90
> 2023-10-30 16:01:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:01:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:02:15 	 POST /airsend/bind 90
> 2023-10-30 16:02:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:02:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:03:15 	 POST /airsend/bind 90
> 2023-10-30 16:03:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:03:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:04:15 	 POST /airsend/bind 90
> 2023-10-30 16:04:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:04:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:05:15 	 POST /airsend/bind 90
> 2023-10-30 16:05:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:05:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:06:15 	 POST /airsend/bind 90
> 2023-10-30 16:06:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:06:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:07:15 	 POST /airsend/bind 90
> 2023-10-30 16:07:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:07:15 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:08:39 	 Started as daemon
> 2023-10-30 16:08:57 	 GET /airsend/close 0
> 2023-10-30 16:08:57 	 handler : size 0 ; new 0x7f6984000df0
> 2023-10-30 16:08:57 	 xxxx::xxxx:xxxx:xxxx:xxxx - GET /airsend/close 0
> 2023-10-30 16:08:57 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:09:06 	 POST /airsend/bind 90
> 2023-10-30 16:09:06 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:09:06 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:09:31 	 POST /airsend/transfer 117
> 2023-10-30 16:09:31 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/transfer 117
> 2023-10-30 16:09:31 	 xxxx::xxxx:xxxx:xxxx:xxxx - {"wait":true,"channel":{"id":"25455","source":"233575"},"thingnotes":{"notes":[{"method":1,"type":1,"value":8}]}}
> 2023-10-30 16:09:31 	 xxxx::xxxx:xxxx:xxxx:xxxx - wait 25 - trevents 1
> 2023-10-30 16:09:36 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 500
> 2023-10-30 16:10:02 	 POST /airsend/bind 90
> 2023-10-30 16:10:02 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:10:02 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:11:02 	 POST /airsend/bind 90
> 2023-10-30 16:11:02 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:11:02 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:12:02 	 POST /airsend/bind 90
> 2023-10-30 16:12:02 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/bind 90
> 2023-10-30 16:12:02 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:12:09 	 GET /airsend/close 0
> 2023-10-30 16:12:09 	 xxxx::xxxx:xxxx:xxxx:xxxx - GET /airsend/close 0
> 2023-10-30 16:12:09 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 200
> 2023-10-30 16:14:17 	 POST /airsend/transfer 117
> 2023-10-30 16:14:17 	 xxxx::xxxx:xxxx:xxxx:xxxx - POST /airsend/transfer 117
> 2023-10-30 16:14:17 	 xxxx::xxxx:xxxx:xxxx:xxxx - {"wait":true,"channel":{"id":"25455","source":"241767"},"thingnotes":{"notes":[{"method":1,"type":1,"value":8}]}}
> 2023-10-30 16:14:17 	 xxxx::xxxx:xxxx:xxxx:xxxx - wait 25 - trevents 1
> 2023-10-30 16:14:23 	 xxxx::xxxx:xxxx:xxxx:xxxx - response 500

**Comment by rezzalex** [comment]
Cela fonctionne avec l'adresse IPV4 mais plus IP v6 ....

**Comment by FlyingDomotic** [comment]
A priori, ça semble être un souci entre le Web service AirSend et le boîtier AirSend. C'est plutôt à eux qu'il faut poser la question.

**Comment by rezzalex** [comment]
J'ai déjà pas mal investigué avec eux; ils incriminaient les containers qui ne pourraient pas router les adresses IP V6, sauf que ca marchait très bien comme ca avant ....

**Comment by FlyingDomotic** [comment]
Des nouvelles ?
Je peux faire quelque chose, ou fermer l'issue ?
