### ISSUE TITLE
[Suggestion pour les prérequis, le web service Airsend]

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#2]
Bonjour,

Je propose d'aider les utilisateurs à facilement obtenir leur webservice airsend dans un container.
je me suis inspiré de https://github.com/devmel/hass_airsend-addon pour créer mon docker file.

Voici le fichier Docker : 

> FROM alpine:latest
COPY runAirsend.sh /runAirsend.sh
RUN chmod a+x /runAirsend.sh
#Install AirSendWebService
RUN mkdir -p /home && cd /home && wget http://devmel.com/dl/AirSendWebService.tgz && tar -zxvf AirSendWebService.tgz && chmod -R 777 bin
#Start AirSendWebService
CMD ["sh", "runAirsend.sh"]

et le fichier "_runAirsend.sh_" qui lance le airsend webservice au démarrage : 

>#!/bin/ash
#arch="$(apk --print-arch)"
#case "$arch" in \
		#aarch64) arch='arm64' ;; \
		#armv7) arch='arm' ;; \
		#amd64) arch='x86_64' ;; \
		#i386) arch='x86' ;; \
	#esac;
#echo "AirSendWebService arch ${arch}"
#./bin/unix/${arch}/AirSendWebService
/home/bin/unix/x86_64/AirSendWebService
sleep infinity

J'ai harcodé la partie détection automatique de l'architecture car ma commande print-arch ne fonctionnait pas avec l'image Alpine.

**Comment by FlyingDomotic** [comment]
J'ai ajouté un pointeur sur cette page dans le README.md.
Merci pour l'exemple !
