### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#3]
Dans mon fichier de conf .json, j'ai enelvé les parties
`"protocolToListen"` : 12345,
et
`mapping` []

voila l'erreur que j'ai et qui revient tout le temps : 

`Error: AirSend: Error 405 in POST http://127.0.0.1:33863/airsend/bind, data {"duration": 0, "channel": {"id": }, "callback": "http://127.0.0.1/airsend.php"}`

**Comment by FlyingDomotic** [comment]
C'est corrigé avec la dernière version. Merci de m'avoir signalé l'erreur.
