### ISSUE TITLE
cant get blinds to work

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#5]
quand j'essaie d'utiliser mes volets roulants créés sou DZ par le plugin : 

`Error: AirSend: Command: "Close" not supported yet for AirSend - Volets Chambre parents. Please ask for support.`

et pareil pour "Open"

**Comment by FlyingDomotic** [comment]
C'est ajouté dans la dernière version. Merci pour la remontée !
