### ISSUE TITLE
les niveaux de logs ne fonctionnent pas

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#7]
on dirait que les niveaux de logs ne fonctionnent pas, je ne vois jamais trop rien, même en changeant les niveaux de logs...

**Comment by FlyingDomotic** [comment]
On est d'accord sur le fait que le plug-in est bien redémarré après les changements de niveau de log ?
On peut redémarrer un plug-in, soit en redémarrant Domoticz, soit en faisant la modif dans les paramètres du plug-in et en cliquant sur "Modifier". Attention, une erreur courante est de cliquer sur "Ajouter", ce qui fait que le plug-in tourne plusieurs fois ...

**Comment by FlyingDomotic** [comment]
Est-ce que le souci est réglé ?

**Comment by rezzalex** [comment]
Bonjour,

oui le niveau de log semble maintenant pris en compte lors du redémarrage du plug-in
