### ISSUE TITLE
[Enhancement] configure listening in UI

### ISSUE THREAD

**Issue by rezzalex** [FlyingDomotic/domoticz-airsend-plugin#9]
Cela pourrait être super de pouvoir, à partir de l'UI du plugin DZ, du plus prioritaire au moins :
 - activer / désactiver l'écoute
 - spécifier le protocole d'écoute
 - mapper les devices avec d'autres télécommandes

A défaut ou en attendant,  comment commenter les lignes dans le fichier de conf . Json ?

j'ai essayé //, #, ou /* */ , sans succès

**Comment by FlyingDomotic** [comment]
Le souci avec l'UI du plug-in est qu'on ne peut donner que 6 paramètres, le 6eme état traditionnellement le niveau de log, ce qui n'en laisse que 5. Ce qui fait qu'on est rapidement confronté, si le plug-in demande quelques paramètres, à utiliser un autre moyen. Le fichier de configuration est une bonne idée.

L'avantage, c'est que si on permet de saisir le nom du fichier de configuration (ce qui est le cas), il est possible d'en créer plusieurs et de passer de l'un à l'autre.

Au-delà ce ça, qu'elles seraient les cas d'utilisations où on souhaiterait ne plus écouter un protocole ? Et en changer à la volée, sachant qu'on peut émettre sur tous les protocoles en même temps, mais ne recevoir qu'un seul, et qu'il faut dans tous les cas que les télécommandes qu'on écoute soient préalablement définies dans AirSend, donc dans configuration.yaml ?

Pour `mapper les devices avec d'autres télécommandes`, j'ai pas compris. Qu'est-ce que vous voulez faire ?

**Comment by rezzalex** [comment]
Merci, le changement de fichier de conf est en effet aisé, je n'y avait pas pensé.

Pour le mappage de la télécommande, j'ai expliqué dans l'autre post.
Je vais demander à Devmel pourquoi ce retour d'Etat ne fonctionne pas ...
